name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unittest:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.3', '7.4']

    name: PHP ${{ matrix.php-versions }} Test

    steps:

      - name: Checks out
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-progress

      - name: Test with phpunit
        run: composer testWithCoverage
